### ISSUE TITLE
snarkJS: Error: Scalar size does not match

### ISSUE THREAD

**Issue by Komari-Koshigaya** [iden3/snarkjs#103]
**With**:
`circuit.circom`
```circom
template Multiplier() {
    signal input a;
    signal input b;
    signal output c;

    c <== a*b;
}
component main = Multiplier();
```
and `input.json`
```json
{
    "a": 1,
    "b": 12
}
```

**execute** 
```shell
circom circuit.circom --r1cs --wasm --sym
snarkjs zkey new circuit.r1cs powersOfTau28_hez_final_10.ptau circuit_0000.zkey
snarkjs zkey contribute circuit_0000.zkey circuit_final.zkey -e="random text"

snarkjs groth16 fullprove input.json circuit.wasm circuit_final.zkey proof.json public.json
```
**I get:**
```shell
❯ snarkjs groth16 fullprove input.json circuit.wasm circuit_final.zkey proof.json public.json
[ERROR] snarkJS: Error: Scalar size does not match
    at _multiExp (snarkjs\node_modules\ffjavascript\build\main.cjs:5467:19)
    at WasmCurve.multiExpAffine (snarkjs\node_modules\ffjavascript\build\main.cjs:5504:22)
    at groth16Prove (snarkjs\build\cli.cjs:5539:33)
    at async groth16FullProve (snarkjs\build\cli.cjs:5877:12)
    at async Object.groth16FullProve$1 [as action] (snarkjs\build\cli.cjs:8289:36)
    at async clProcessor (snarkjs\build\cli.cjs:280:21)
```

**Comment by Komari-Koshigaya** [comment]
> **With**:
> `circuit.circom`
> 
> ```
> template Multiplier() {
>     signal input a;
>     signal input b;
>     signal output c;
> 
>     c <== a*b;
> }
> component main = Multiplier();
> ```
> 
> and `input.json`
> 
> ```json
> {
>     "a": 1,
>     "b": 12
> }
> ```
> 
> **execute**
> 
> ```shell
> circom circuit.circom --r1cs --wasm --sym
> snarkjs zkey new circuit.r1cs powersOfTau28_hez_final_10.ptau circuit_0000.zkey
> snarkjs zkey contribute circuit_0000.zkey circuit_final.zkey -e="random text"
> 
> snarkjs groth16 fullprove input.json circuit.wasm circuit_final.zkey proof.json public.json
> ```
> 
> **I get:**
> 
> ```shell
> ❯ snarkjs groth16 fullprove input.json circuit.wasm circuit_final.zkey proof.json public.json
> [ERROR] snarkJS: Error: Scalar size does not match
>     at _multiExp (snarkjs\node_modules\ffjavascript\build\main.cjs:5467:19)
>     at WasmCurve.multiExpAffine (snarkjs\node_modules\ffjavascript\build\main.cjs:5504:22)
>     at groth16Prove (snarkjs\build\cli.cjs:5539:33)
>     at async groth16FullProve (snarkjs\build\cli.cjs:5877:12)
>     at async Object.groth16FullProve$1 [as action] (snarkjs\build\cli.cjs:8289:36)
>     at async clProcessor (snarkjs\build\cli.cjs:280:21)
> ```

no problem if I modify `signal input a;` to `signal private input a:`, which means there  ought to be a private input?

**Comment by a2468834** [comment]
(1) `private` does not use anymore.
According to v2 [docs](https://docs.circom.io/circom-language/signals/), signals are always considered private. Hence, you could just write `signal input a;` .

(2) If I did the some things and put the same codes you wrote, I got no error message in v2 Circom.

(3) Another wired problem🤔
If I add one more line of code `b === 12;`, it produced the same error msg as yours.
- `circuit.circom`
```
pragma circom 2.0.0;
 
template mainFunc() {
	signal input a;
 	signal input b;
 	signal output c;
 	
 	b === 12; // Add this line
 	c <== a * b;
}

component main = mainFunc();
```
- `input.json`
```
{
    "a": 1,
    "b": 12
}
```
- Execute
```
$ circom circuit.circom --r1cs --wasm --sym
$ snarkjs zkey new circuit.r1cs powersOfTau28_hez_final_19.ptau circuit_0000.zkey
$ snarkjs zkey contribute circuit_0000.zkey circuit_final.zkey -e=randStr
$ snarkjs zkey export verificationkey circuit_final.zkey verification_key.json
$ node --trace-warnings ./circuit_js/generate_witness.js ./circuit_js/circuit.wasm ../input.json witness.wtns
$ snarkjs groth16 prove circuit_final.zkey witness.wtns proof.json public.json
```
- Get error message again
```
$ snarkjs groth16 prove circuit_final.zkey witness.wtns proof.json public.json
[ERROR] snarkJS: Error: Scalar size does not match
    at _multiExp (/usr/lib/node_modules/snarkjs/node_modules/ffjavascript/build/main.cjs:5467:19)
    at WasmCurve.multiExpAffine (/usr/lib/node_modules/snarkjs/node_modules/ffjavascript/build/main.cjs:5504:22)
    at groth16Prove (/usr/lib/node_modules/snarkjs/build/cli.cjs:5539:33)
    at async Object.groth16Prove$1 [as action] (/usr/lib/node_modules/snarkjs/build/cli.cjs:8268:36)
    at async clProcessor (/usr/lib/node_modules/snarkjs/build/cli.cjs:280:21)
```

**Comment by JofArnold** [comment]
Just had this problem again (different reason) and stumbled across this issue again. Looking at your code sample above, @Komari-Koshigaya, you are missing an intermediate signal. The following should work for you:

```
template Multiplier() {
    signal input a;
    signal input b;
    signal output c;
    signal i; // Add this
    i <-- a * b; // ... and this
    c <== i;
}
component main = Multiplier();
```

**Comment by a2468834** [comment]
Thank you @JofArnold for giving everyone these useful suggestions.

> For me in my use-case the error was due to not having a return value after the assertion. Returning the field value `1` was enough.

May I ask you about what you mean "having a return value after the assertion"?
I used to think `b === 12` in Circom should work the same as `assert (b == 12)` in python or c++.
The point I could not get is why did you say "===" would have a return value?

**Comment by Komari-Koshigaya** [comment]
@JofArnold This method doesn't work for me, does it work for you @a2468834?
Only adding private input can solve the problem for me.

**Comment by JofArnold** [comment]
@a2468834 Regarding return I was wrong; I was thinking of ZoKrates

Regarding `===` I also read it as `assert`. In a browser it will throw if false.

**Comment by JofArnold** [comment]
@Komari-Koshigaya Are you executing those commands in the terminal or indirectly via a script (eg node). Although I don't think this is your problem when running my scripts in a monorepo I found that there was a package that unsealed circom 0.5 so that script was using that version and not my global 2.0.1. If you are running it as I say, maybe put `yarn why circom` or `which circom` before the failing line.

**Comment by Komari-Koshigaya** [comment]
@JofArnold  Do you mean circom@2.0.1 should be installed？Is it not recommended to use old circom?
I installed circom@0.5.46 and executed those commands in the terminal。

**Comment by JofArnold** [comment]
@Komari-Koshigaya You may have some success on 0.5 but 2.0.x (compiled and installed globally using cargo) is the way. This explains why `private` works in the example above. I recommend you use 2.0.x; it's better in every way

**Comment by jp4g** [comment]
Using 2.0.4 and l so far have followed directions here in #114. Any insights on what I am doing wrong greatly appreciated

**Comment by Philogy** [comment]
Also getting this error as soon as I define some public inputs via the `component main {public [a,b]}` syntax, how do I resolve? I can't even get it to work with a very simple `c <== a * b` multiplication circuit

**Comment by akayi07** [comment]
Hi, I know why `b === 12` failed now. Because 12 in circom is Field element values. Type of 12 and value in input.json is not same. If you use `signal g; g <-- b; g === 12`, it succeed. So `<--` converts type of input value to Field element values

**Comment by akayi07** [comment]
Hi，I know why `b === 12` failed. Because 12 in circom is Field element values. Type of 12 and values in input.json is different. If you use `signal g; g <-- b; g === 12`, it will succeed. So `<--` converts type of input values to Field element values.

**Comment by Iverson-cui** [comment]
> (1) `private` does not use anymore. According to v2 [docs](https://docs.circom.io/circom-language/signals/), signals are always considered private. Hence, you could just write `signal input a;` . If I did the some things and put the same codes you wrote, I got no error message in v2 Circom.
> 
> (2) Another wired problem🤔 If I add one more line of code `b === 12;`, it produced the same error msg as yours.
> 
> * `circuit.circom`
> 
> ```
> pragma circom 2.0.0;
>  
> template mainFunc() {
> 	signal input a;
>  	signal input b;
>  	signal output c;
>  	
>  	b === 12; // Add this line
>  	c <== a * b;
> }
> 
> component main = mainFunc();
> ```
> 
> * `input.json`
> 
> ```
> {
>     "a": 1,
>     "b": 12
> }
> ```
> 
> * Execute
> 
> ```
> $ circom circuit.circom --r1cs --wasm --sym
> $ snarkjs zkey new circuit.r1cs powersOfTau28_hez_final_19.ptau circuit_0000.zkey
> $ snarkjs zkey contribute circuit_0000.zkey circuit_final.zkey -e=randStr
> $ snarkjs zkey export verificationkey circuit_final.zkey verification_key.json
> $ node --trace-warnings ./circuit_js/generate_witness.js ./circuit_js/circuit.wasm ../input.json witness.wtns
> $ snarkjs groth16 prove circuit_final.zkey witness.wtns proof.json public.json
> ```
> 
> * Get error message again
> 
> ```
> $ snarkjs groth16 prove circuit_final.zkey witness.wtns proof.json public.json
> [ERROR] snarkJS: Error: Scalar size does not match
>     at _multiExp (/usr/lib/node_modules/snarkjs/node_modules/ffjavascript/build/main.cjs:5467:19)
>     at WasmCurve.multiExpAffine (/usr/lib/node_modules/snarkjs/node_modules/ffjavascript/build/main.cjs:5504:22)
>     at groth16Prove (/usr/lib/node_modules/snarkjs/build/cli.cjs:5539:33)
>     at async Object.groth16Prove$1 [as action] (/usr/lib/node_modules/snarkjs/build/cli.cjs:8268:36)
>     at async clProcessor (/usr/lib/node_modules/snarkjs/build/cli.cjs:280:21)
> ```

Excuse me. You seem to be good at this "Scalar size not match" bug. I have come across the same issue. Can you tell me exactly what has caused this problem or what can I do to fix it?

**Comment by OBrezhniev** [comment]
"Scalar size not match" means there's no non-linear constraints, which means there's nothing to prove in case of groth16, because linear constraints are removed.

Never use `<--` (unless you REALLY know what you are doing) - it's not adding constraints. But when used signal which was assigned value in this way should always be properly constrained later.

Assert is not adding constraints too. Attacker can just skip asserts from witness calculation code and get valid proof for incorrect inputs. Use asserts only to check constants & expressions which circom compiler can evaluate during compilation, e.g. you can check with assert that template param does not go out of boundaries of some signal array you have.

Also in some cases compiler may remove constraints and even private inputs during compilation:
https://docs.circom.io/circom-language/circom-insight/simplification/
