### ISSUE TITLE
Can't run fullProve function

### ISSUE THREAD

**Issue by vuvth** [iden3/snarkjs#107]
I try running the snarkjs@0.4.10 fullProve function on node and browser but it returns the error. I tried to run only prove and it work well, not returning any error.

More info about env: 
- Hardware : Macbook M1 
- node v14.18.1
- snarkjs 0.4.10
- circom 2.0
Error: 
```bash
snarkjs.min.js:1 Uncaught (in promise) LinkError: WebAssembly.instantiate(): Import #0 module="runtime" function="exceptionHandler" error: function import requires a callable
    at lg (snarkjs.min.js:1)
    at async Gg (snarkjs.min.js:1)
    at async Object.fullProve (snarkjs.min.js:1)
    at async HTMLButtonElement.calculateProof ((index):36)
```
 
Thank you for your help!

**Comment by connorbode** [comment]
I've just encountered this issue using circom compiler 2.0.1. This issue should perhaps not be closed. 

I've had no trouble using the `generate_witness.js` file created by the circom compiler + `snarkjs plonk prove`. That leads me to believe the generated wasm is ok.

However when using `snarkjs plonk fullprove` the same WebAssembly exception mentioned in the issue description occurs.

**Comment by connorbode** [comment]
I've found a reasonable workaround based on the `generate_witness.js` file. 

For `Circuit.circom`, the file `Circuit_js/witness_calculator.js` can be used in JS as follows:

```javascript
const snarkjs = require('snarkjs')
const fs = require('fs')

const wc = require('/path/to/Circuit_js/witness_calculator.js')
const wasm = '/path/to/Circuit_js/Circuit.wasm'
const zkey = '/path/to/Circuit_final.zkey'
const INPUTS_FILE = '/tmp/inputs'
const WITNESS_FILE = '/tmp/witness'

const generateWitness = async (inputs) => {
  writeFileSync(INPUTS_FILE, JSON.stringify(inputs))
  const input = JSON.parse(fs.readFileSync(INPUTS_FILE, "utf8"));
  const buffer = fs.readFileSync(wasm);
  const witnessCalculator = await wc(buffer)
  const buff = await witnessCalculator.calculateWTNSBin(input,0);
  fs.writeFileSync(WITNESS_FILE, buff)
}

const main = async () => {
  const inputSignals = { enabled: 1, in: [1, 1] } // replace with your signals
  await generateWitness(inputSignals)
  const { proof, publicSignals } = await snarkjs.plonk.prove(zkey, WITNESS_FILE);
}

```

**Comment by michal-wrzosek** [comment]
thnaks @connorbode 
I will also look for some client-side workaround as well. I'm curious what is the core problem here. It would be cool to make snarkjs compatible with new circom.

**Comment by connorbode** [comment]
@michal-wrzosek if you used any of that code, please check the updated `generateWitness` function. I pulled the code from `witness_calculator.js` and made quick edits. I didn't realize but the code (1) wrote JSON serialized inputs to disk (2) read the inputs back immediately after (whoops). This caused issues with numbers > 32 bytes in size.

**Comment by sragss** [comment]
This is definitely happening during the witness creation in `snarkjs/src/wtns_calculate.js`.

A cleaner workaround that I found (that does not require writing to file) is that you can call `snarkjs.plonk.prove(zkey_file, witness_buffer)` rather than passing the witness file name.

My best guess is that the generated WASM is not compatible with this version of the circom runtime resulting in more function definitions being required here: https://github.com/iden3/circom_runtime/blob/master/js/witness_calculator.js#L52-L88

**Comment by sragss** [comment]
[This is the version](https://github.com/iden3/circom/blob/master/code_producers/src/wasm_elements/witness_calculator.js) that `witness_calculator.js` uses, which is generated by the circom `cmd` tool. Whereas [this is the version](https://github.com/iden3/circom_runtime/blob/d582016ddc50497d236a7930c6f99ddb3123e1f8/js/witness_calculator.js) that `snarkjs.plonk.fullProve` and `snarkjs.wtns.wtns_calculate` use.

**Comment by hexLancel** [comment]
Have you had a problem like   

Line 235:15:  'BigInt' is not defined  no-undef

When using the workaround ? Any solution ?
