### ISSUE TITLE
Solidity Verifier fails to compile, with 'expected token LBrace, got reserved keyword 'pure'

### ISSUE THREAD

**Issue by glamperd** [iden3/snarkjs#11]
Pragma in set to ^0.4.14 in the solidity tempalte. When compiling with version 0.4.14, the contract fails to compile, throwing `ParserError: expected token LBrace, got reserved keyword 'pure'`.

The compile works OK with v0.4.17.

**Comment by jbaylina** [comment]
New version 0.3 ported the solidity code to 0.6
I tested and in works ok.
