### ISSUE TITLE
Function to generate solidity parameters

### ISSUE THREAD

**Issue by connorbode** [iden3/snarkjs#112]
I had a lot of trouble discovering how to generate parameters to pass to an ethersjs contract function. It's possible that I've gone in the wrong direction, but I wanted to document the steps I took and the suggestions I have.

First, the `unstringifyBigInts` function is necessary & can be imported as follows:

```
const ffjavascript = require('ffjavascript')
const unstringifyBigInts = ffjavascript.utils.unstringifyBigInts
```

Next, here is the code I've used to submit a `verifyProof` call. Note that `verifierContract` is an instance of an ethersjs contract.

```
const { proof, publicSignals } = await snarkjs.plonk.prove(ZKEY_PATH, WITNESS_FILE)
const calldata = await snarkjs.plonk.exportSolidityCallData(unstringifyBigInts(proof), unstringifyBigInts(publicSignals))
const calldataSplit = calldata.split(',')
const proofFormatted = calldataSplit[0]
const publicSignalsFormatted = JSON.parse(values[1]).map(x => BigInt(x).toString())
const output = await verifierContract.verifyProof(proofFormatted, publicSignalsFormatted)
```

This all took a while for me to put together. A function like `snarkjs.plonk.generateSolidityParams(proof, publicSignals)` which formats the `proof` and `publicSignals` for web3 / ethers would be very useful for people new to snarkjs.

Hopefully this helps someone!

**Comment by phated** [comment]
You should no longer need to unstringifyBigInts as of #146 - Can you test snarkjs v0.4.17 ?
