### ISSUE TITLE
Error while running groth16.fullProve in Node (wc.calculateBinWitness is not a function)

### ISSUE THREAD

**Issue by zhvng** [iden3/snarkjs#126]
I was following the guide in the readme but when I tried calling ` snarkjs.groth16.fullProve({a: 10, b: 21}, "circuit.wasm", "circuit_final.zkey");` (under the "Using Node" section https://github.com/iden3/snarkjs#using-node) I get this error:

```
(node:20922) UnhandledPromiseRejectionWarning: TypeError: wc.calculateBinWitness is not a function
    at wtnsCalculate (.../node_modules/snarkjs/build/main.cjs:1131:24)
    at async Object.groth16FullProve [as fullProve] (.../node_modules/snarkjs/build/main.cjs:1163:5)
    at async run (.../index.js:5:38)
```

All the CLI stuff works fine and I can call `snarkjs.groth16.prove` just fine if I pre-generate the witness file, but it appears fullProve is broken for me.

I'm on circom compiler v2.0.3 which I just cloned from github about an hour ago.

**Comment by zhvng** [comment]
Ok turns out this is the same as #107

If anyone's looking for a solution, here's a way to do it using the generated witness_calculator 

```
    const wc = require("./witness_calculator");
...
    const buffer = fs.readFileSync("circuit.wasm");
    const witnessCalculator = await wc(buffer);
    const witnessBuffer = await witnessCalculator.calculateWTNSBin({a: 3, b: 11}, 0);
    const { proof, publicSignals } = await snarkjs.groth16.prove('/path/to/.zkey', witnessBuffer);
```

**Comment by minism** [comment]
> Ok turns out this is the same as #107
> 
> If anyone's looking for a solution, here's a way to do it using the generated witness_calculator
> 
> ```
>     const wc = require("./witness_calculator");
> ...
>     const buffer = fs.readFileSync("circuit.wasm");
>     const witnessCalculator = await wc(buffer);
>     const witnessBuffer = await witnessCalculator.calculateWTNSBin({a: 3, b: 11}, 0);
>     const { proof, publicSignals } = await snarkjs.groth16.prove('/path/to/.zkey', witnessBuffer);
> ```

How is `witness_calculator` generated in your example?
