### ISSUE TITLE
generate witness file

### ISSUE THREAD

**Issue by LuozhuZhang** [iden3/snarkjs#142]
If u don't have generate_witness.js file
```
circuit_js$ node generate_witness.js circuit.wasm ../input.json ../witness.wtns
```

You can run this code to generate witness file
```
snarkjs wtns calculate circuit.wasm input.json witness.wtns
```

More recommend the last one, this issue refer to #91

**Comment by phated** [comment]
As discovered with #217, circom doesn't follow SemVer and can break snarkjs at any time. I'm not inclined to recommend people use snarkjs for witness calculation since it might be broken while we try to catch up to them.
