### ISSUE TITLE
Vendor data present and stated as malicious since version 0.4.17

### ISSUE THREAD

**Issue by galaktipus** [iden3/snarkjs#147]
### Version

v0.4.16 and v0.4.17

### Description

Hey there,

My name is Tamir and I run security & quality assessments for npm libraries using Diffend.io.

While reviewing the changes for this lib, I noticed, that the vendor directory is being included.

Is this needed? Usually, it's added by mistake and causes:

a) confusion
b) problems when tracking changes
c) extensive library size

ref: [LINK](https://github.com/iden3/snarkjs/tree/v0.4.17/env/lib/python3.9/site-packages/pip/_vendor/distlib)

Note that the according to virus total, one vendor is now alerting the added file `w32.exe` as malicious.
https://www.virustotal.com/gui/file/949b6765d794c53656c9afc45b90d9a2cfcae6bb30444086b29225f19242217b

If the presence of vendor data is valid I would love the reasoning. Thanks!

**Comment by phated** [comment]
It looks like an installation of python was added to the package by mistake. Those aren't malicious, but they do explode the package size. We'll be removing the `env` directory that got added to the repository.

**Comment by phated** [comment]
This was removed and released as 0.4.18
