### ISSUE TITLE
Error on Plonk call data generation

### ISSUE THREAD

**Issue by skardas** [iden3/snarkjs#149]
If you look at the link:
https://github.com/iden3/snarkjs/blob/31f7867fa031c7e2c056331a7a3d4c6c29d5de35/build/cli.cjs#L7759

you will see:

 const pub = unstringifyBigInts$1(_proof);
    const proof = unstringifyBigInts$1(_pub);

this is wrong so we get error, you can fix it as follows:

 const **pub** = unstringifyBigInts$1(**_pub**);
    const **proof** = unstringifyBigInts$1(**_proof**);

**Comment by skardas** [comment]
similar error is here

https://github.com/iden3/snarkjs/blob/31f7867fa031c7e2c056331a7a3d4c6c29d5de35/build/cli.cjs#L6002

**Comment by phated** [comment]
Duplicate of #148 - want to submit a PR?
