### ISSUE TITLE
Getting Error on zkSnark.setup(circuit) "setup ist not a function"

### ISSUE THREAD

**Issue by MarioHSMW** [iden3/snarkjs#16]
When testing snarkjs on my node console and try to do the setup by const setupt = zkSnark.setup(circuit);
it gives me the error setup is not a function.

**Comment by ochikov** [comment]
Hello @MarioHSMW 
You can see my issue here, and you will be able to clarify how to use zkSnark setup function: 
https://github.com/iden3/snarkjs/issues/18

Thank you.

**Comment by jbaylina** [comment]
Take a look at new version 0.3 
The setup is done now with the MPC.
You should have any problem now.
