### ISSUE TITLE
Angular error during compilation - Can't resolve 'crypto'

### ISSUE THREAD

**Issue by ochikov** [iden3/snarkjs#17]
Hello,
I am running Angular and requiring 'snarkjs' library.
I have the following error during compilation: 

```
ERROR in ../node_modules/snarkjs/src/zqfield.js
Module not found: Error: Can't resolve 'crypto' in '/Users/ognyanchikov/angular-zk/node_modules/snarkjs/src'
```

The problem comes from line 35 of that file (zqfield.js). It tries to require 'crypto' library, because 'window' is still undefined (during compilation of Angular project), but in Angular, the 'crypto' module is not included. The 'webpack' configuration is turning it off, as well as other modules, e.g 'fs'.

These are my packages versions:

```
Angular CLI: 7.1.4
Node: 8.10.0
OS: darwin x64
Angular: 7.1.4

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.4
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/build-webpack     0.11.4
@angular-devkit/core              7.1.4
@angular-devkit/schematics        7.1.4
@ngtools/webpack                  7.1.4
@schematics/angular               7.1.4
@schematics/update                0.11.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1
```

**Comment by mohsenmahoski** [comment]
add this to your `package.json` and run it again
```
	"browser": {
		"fs": false,
		"path": false,
		"os": false,
		"crypto": false,
		"stream": false,
		"http": false,
		"tls": false,
		"zlib": false,
		"https": false,
		"net": false
	}
```

**Comment by FernandoArteaga** [comment]
I just added, and the console shows no error, but in the browser, I'm getting this error:

index.js:43 Uncaught ReferenceError: global is not defined
    at Object../node_modules/buffer/index.js (index.js:43)
    at __webpack_require__ (bootstrap:83)
    at Object../node_modules/safe-buffer/index.js (index.js:2)
    at __webpack_require__ (bootstrap:83)
    at Object../node_modules/jws/lib/sign-stream.js (sign-stream.js:2)
    at __webpack_require__ (bootstrap:83)
    at Object../node_modules/jws/index.js (index.js:2)
    at __webpack_require__ (bootstrap:83)
    at Object../node_modules/jsonwebtoken/decode.js (decode.js:1)
    at __webpack_require__ (bootstrap:83)

**Comment by bleuscyther** [comment]
> I just added, and the console shows no error, but in the browser, I'm getting this error:
> 
> index.js:43 Uncaught ReferenceError: global is not defined
> at Object../node_modules/buffer/index.js (index.js:43)
> at **webpack_require** (bootstrap:83)
> at Object../node_modules/safe-buffer/index.js (index.js:2)
> at **webpack_require** (bootstrap:83)
> at Object../node_modules/jws/lib/sign-stream.js (sign-stream.js:2)
> at **webpack_require** (bootstrap:83)
> at Object../node_modules/jws/index.js (index.js:2)
> at **webpack_require** (bootstrap:83)
> at Object../node_modules/jsonwebtoken/decode.js (decode.js:1)
> at **webpack_require** (bootstrap:83)

@FernandoArteaga  add this to your polyfill.ts

```typescript
(window as any).global = window;
(window as any).process = {};
(window as any).process = window;
(window as any).process.browser = true;
(window as any).process.version = '';
(window as any).process.versions = {node: false};
(window as any).process.nextTick = (() => {
    const canSetImmediate = typeof window !== 'undefined'
        && (window as any).setImmediate;
    const canPost = typeof window !== 'undefined'
        && window.postMessage && window.addEventListener;
    if (canSetImmediate) {
        return (f) => {
            return (window as any).setImmediate(f);
        };
    }
    if (canPost) {
        const queue = [];
        window.addEventListener('message', (ev) => {
            const source = ev.source;
            if ((source === window || source === null) && ev.data === 'process-tick') {
                ev.stopPropagation();
                if (queue.length > 0) {
                    const fn = queue.shift();
                    fn();
                }
            }
        }, true);
        return function nextTick(fn) {
            queue.push(fn);
            window.postMessage('process-tick', '*');
        };
    }
    return function nextTick(fn) {
        setTimeout(fn, 0);
    };
})();
(window as any).global.Buffer = (window as any).global.Buffer || require('buffer').Buffer;
```

I can't remember if i installed Buffer (if it help, its installed) :
```console
npm  -i -s buffer
```

**Comment by ochikov** [comment]
My solution is as follows:
I made a file `patch-webpack.js` with this code:

```const fs = require('fs');
const f = 'node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/browser.js';

fs.readFile(f, 'utf8', function (err, data) {
	if (err) {
		return console.log(err);
	}
	let result = data.replace(/node: false/g, "node: {crypto: true, stream: true, fs: 'empty', net: 'empty'}");

	fs.writeFile(f, result, 'utf8', function (err) {
		if (err) return console.log(err);
	});
});```

then in `package.json` on `postinstall` need to put this line: 

 ```"postinstall": "node patch-webpack.js"```

**Comment by jbaylina** [comment]
New version 0.3 is tested for browser. Please take a look.

**Comment by tanrobles** [comment]
> add this to your `package.json` and run it again
> 
> ```
> 	"browser": {
> 		"fs": false,
> 		"path": false,
> 		"os": false,
> 		"crypto": false,
> 		"stream": false,
> 		"http": false,
> 		"tls": false,
> 		"zlib": false,
> 		"https": false,
> 		"net": false
> 	}
> ```

Working Fine in Ionic 5 with Angular 9.
Thanks!
