### ISSUE TITLE
Circuit_js folder not created

### ISSUE THREAD

**Issue by nullllllion** [iden3/snarkjs#191]
Hey team. I have been using snarkjs to calculate the witness and according to its docs, circuit_js folder will be created automatically when compiling the circuit using circom, but it is not the case on my end. Does the API is changed, or am I doing something wrong?

I am working on Mac.

**Comment by phated** [comment]
Hey @RahulBansal123 - I think you might be trying to use `circom` installed from npm instead of the Rust compiler which is commonly referred to as "Circom 2"
