### ISSUE TITLE
Semaphore MIT license

### ISSUE THREAD

**Issue by cedoor** [iden3/snarkjs#199]
Dear Iden3 contributors,

We want to license [Semaphore](https://github.com/semaphore-protocol/) under MIT. The project is built using Circom and SnarkJS which are licensed GPL3. Specifically the use of the Verifier.sol template raises concerns if Semaphore has to inherit the GPL3 license from Circom & SnarkJS. As previously discussed with Jordi we want to resolve any doubt for Semaphore and other projects with this issue. Please indicate your consent by answering “I agree”.

_Jordi Baylina and other contributors to GPLv3-licensed components in the Semaphore code base, including poseidon.circom, mux1.circom, Verifier.sol, circomlibjs, agree effective July 2022 that the entire code in the Semaphore project and all related documentation and prior versions ("Software") shall be licensed to each other and anyone else under the MIT License. Each contributor who accepts this License Agreement by way of an issue or pull request on the projects' GitHub repository, or by email or click, or by contributing after this License Agreement is published or attached to the Software, or by any other expression of consent, irrevocably agrees under such contributor's copyrights and other intellectual property rights that the MIT License shall apply to the Software. Permissions to use components under the GPLv3 License or other licenses shall continue, but users of the Software shall no longer be required to comply with the GPLv3 License or other licenses so long as they comply with the MIT License._

**Comment by ETHorHIL** [comment]
@jbaylina please let us know if you agree

**Comment by jbaylina** [comment]
I agree!

**Comment by Pandapip1** [comment]
GPLv3 is problematic for libraries since it isn't always clear that applications that use those libraries must also be GPLv3, and can conflict with other licenses (it would in fact conflict with the licenses of the dependencies, had Apache2 not included a GPLv3 clause!). I suggest you switch to MIT as soon as you can.

**Comment by chris05atm** [comment]
@jbaylina - is it possible to link to the Contributor License Agreement used in this repository? And to highlight certain files are MIT vs GPL-3? 

I was looking at [Semaphore](https://github.com/semaphore-protocol/) and then found its use of iden3 code. That discrepancy led me to this GitHub issue.

Seeing @jbaylina 's single-author approval to change from GPL-3 to MIT for Semaphore's use (pleasantly!) surprised me. That typed, changing a multi-authored repo's license retroactively is complicated depending on license. Further digging then noticed this repository had a CLA based on a bot link in one of the [open PRs](https://github.com/iden3/snarkjs/pull/32#issuecomment-547446699). Further reading of the linked (version 2019-08-27) CLA shows:

```
2.3 Outbound License
Based on the grant of rights in Sections 2.1 and 2.2, if We include Your Contribution in a Material, We may license the Contribution under any license, including copyleft, permissive, commercial, or proprietary licenses. As a condition on the exercise of this right, We agree to also license the Contribution under the terms of the license or licenses which We are using for the Material on the Submission Date.
```

I suspect highlighting the CLA and the subsequent allowance of certain files for certain projects would be beneficial to other developers looking at Semaphore and snarkjs and trying to work with the license terms on both projects. Would you be amenable to that with a link back to this GitHub issue?

**Comment by phated** [comment]
This project no longer uses a CLA so the singular author-approval is likely not good enough.

**Comment by imikushin** [comment]
Is moving to MIT license still on the map? (Asking for a friend)

**Comment by phated** [comment]
@imikushin No, SnarkJS and Circom are purposefully GPL3.

**Comment by imikushin** [comment]
@phated Thanks for clarification.
