### ISSUE TITLE
Setup and Witness generation fail for large number of constraints

### ISSUE THREAD

**Issue by druiz0992** [iden3/snarkjs#20]
I am working with circuits with 2^20+ constraints. I wasn't able to obtain a valid circuit or compute witness. Problem is that required memory was too large. Also, I would like not having to rely on JSON file which is inefficient for my needs.

**Comment by jbaylina** [comment]
In the current version, probably this does not apply. But you can run it with node --max-old-space-size /snarkjs/cli.js [params]
