### ISSUE TITLE
how to deal with this problem? "circom circuit.circom --r1cs --wasm --sym"

### ISSUE THREAD

**Issue by wzm397** [iden3/snarkjs#207]
When I execute this command "circom circuit.circom --r1cs --wasm --sym", this problem appears, how should I fix it?
![image](https://user-images.githubusercontent.com/61742432/183299509-c6fcac42-86e3-4e65-84cc-b9fe12a16cc4.png)

**Comment by phated** [comment]
Snarkjs is not written in Rust. You want to open an issue on https://github.com/iden3/circom
