### ISSUE TITLE
Can't use in Chrome Extension 

### ISSUE THREAD

**Issue by JXRow** [iden3/snarkjs#210]
We tried hard, but the wasm dosen't work in chrome extension.
According to https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/, it should work, but it dosen't.
Can anyone show a snarkjs chrom extension demo ?

**Comment by phated** [comment]
> Starting in Chrome 102, Manifest V3 extensions can include wasm-unsafe-eval in the CSP to use WebAssembly files bundled as part of the extension.
