### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by mlshv** [iden3/snarkjs#219]
Hello, snarkjs maintainers and contributors!

I'd like to address the elephant in the room. As for now, snarkjs doesn't work in the browser out of the box, although the README says the opposite:
> It works in node.js as well as directly in the browser.

I might have missed something, but [the example](https://github.com/iden3/snarkjs#in-the-browser) from README doesn't work. I've tried to fix it, but didn't have much of a success because of various errors related to nodejs APIs usages which are not supported in the browser.

Am I doing something wrong or is this problem actually exists? If so, are there any plans for fixing it?

Also I could contribute to it if you lack free hands.

Thank you!

**Comment by phated** [comment]
Snarkjs works great in the browser! Dark Forest uses it [here](https://github.com/darkforest-eth/client/blob/master/index.html#L70). You can download the provided browser bundle from https://github.com/iden3/snarkjs/blob/master/build/snarkjs.min.js

If you are trying to use this with a bundler, you need to actually config your bundler like we do: https://github.com/iden3/snarkjs/blob/master/config/rollup.iife.config.js
