### ISSUE TITLE
Use ECMA-262-standard BigInt

### ISSUE THREAD

**Issue by BrendanEich** [iden3/snarkjs#24]
Hi, fan of the work here, just wondering whether it's possible to use BigInt now that it is at Stage 3 (the last one before the "ready to implement", and BigInts are already in V8, JavaScriptCore, and SpiderMonkey per https://github.com/tc39/proposal-bigint at bottom). And if so, what if any speedup does native BigInt gain? Thanks.

**Comment by jbaylina** [comment]
We are using a wasm implementation of finite fields. This uses montgomery form. And all together is faster that BigInt.
