### ISSUE TITLE
Verifiers for NEAR protocol

### ISSUE THREAD

**Issue by veigajoao** [iden3/snarkjs#303]
Hello guys,

I built Groth16 and Plonk verifiers as smart contracts for the NEAR protocol that are compatible with snarkjs. They are written in Rust with WASM as a target.

Would it be possible/interesting to you to add them to the main lib?

**Comment by phated** [comment]
The problem we've had is that we don't have the bandwidth or experience to review/audit these generators. When I have some time, I plan to prototype a plugin system for these generators but that won't be any time soon.

**Comment by veigajoao** [comment]
Ok, no problem, whenever you're ready to support the plugins just sent me a message.

Meanwhile, in case you have a reference on unofficial contracts that support other chains, I'd be happy to add our implementations there.

For reference:
Groth16: https://github.com/hideyour-cash/hideyour-cash/tree/main/packages/contract-libraries/groth_verifier
Plonk: https://github.com/hideyour-cash/hideyour-cash/tree/main/packages/contract-libraries/plonk_verifier

**Comment by VegeBun-csj** [comment]
@veigajoao maybe this can help with groth16: https://github.com/DoraFactory/snarkjs-bellman-adapter

**Comment by phated** [comment]
I'm going to close this because we aren't accepting new verifiers since we can't ensure the correctness of them. You should follow #340 which will enable custom verifier packages once implemented.
