### ISSUE TITLE
[ERROR] snarkJS: [Error: ENOENT: no such file or directory, open 'pot12_final.ptau'] {   errno: -2,   code: 'ENOENT',   syscall: 'open',   path: 'pot12_final.ptau' }

### ISSUE THREAD

**Issue by forum-120** [iden3/snarkjs#350]
I have this issue when I type _'snarkjs plonk setup circuit.r1cs pot12_final.ptau circuit_final.zkey'_ in terminal

**Comment by phated** [comment]
You need to download or create a ptau file named `pot12_final.ptau` in the directory that you are working in.
