### ISSUE TITLE
Vulnerability allowing double spend

### ISSUE THREAD

**Issue by 0xsaya** [iden3/snarkjs#358]
Looks like in [groth16_verify.js#L44](https://github.com/iden3/snarkjs/blob/e113aecbc5515faf46d23c596b8930dcbb932604/src/groth16_verify.js#L44) we don't check that publicSignals length is less than field modulus. So we will also pass snark proof verification if it fits , allowing double spend.

![double spend](https://user-images.githubusercontent.com/29145046/236403104-5e31db43-e830-472d-ac7a-2a79b88e473c.png)
credit: 0xsaya from Beosin

**Comment by xavi-pinsach** [comment]
We're working on it. I've just published a new branch xpinsach/issue_358 to fix it. You can try if this branch fix your test.

**Comment by 0xsaya** [comment]
hi,sorry, when i use command "npm install -g ..." install this branch, an error occurs :
git-cloneNcciAu/test/plonk_circuit/powersOfTau15_final.ptau
npm encountered unexpected EOF
<img width="565" alt="image" src="https://user-images.githubusercontent.com/29145046/236656344-335cff1a-325b-467c-aa64-b2466888d432.png">

**Comment by themandalore** [comment]
Hey @0xsaya  , would one need to recompile/ redeploy all Verifier contracts due to this bug or is it further down the line?

**Comment by ytrezq** [comment]
Hello, does this bugs only concerns verifiers generated for the Javascript target?

**Comment by 0xsaya** [comment]
@ytrezq Yes, this vulnerability only affects the JavaScript code portion of the snarkjs library. However, we have discovered another vulnerability in many third-party libraries of zk algorithms like groth16. We recommend that this vulnerability be addressed in DApps. If you need to develop a zk DApp, you should pay special attention to it.

**Comment by ytrezq** [comment]
> @ytrezq Yes, this vulnerability only affects the JavaScript code portion of the snarkjs library. However, we have discovered another vulnerability in many third-party libraries of zk algorithms like groth16. We recommend that this vulnerability be addressed in DApps. If you need to develop a zk DApp, you should pay special attention to it. The link is：#383

@0xsaya this does not appear to affect verifiers using nullifiers?

**Comment by mimoo** [comment]
I'm not sure I understand how this allows double spending. If I understand correctly this allows for malleable proofs, but so what? Of course it's nice if snarkjs checks the correct shape of the inputs, but checking for valid public inputs should be on the application side no?

**Comment by ytrezq** [comment]
@mimoo It allowed malleable public inputs.

**Comment by ytrezq** [comment]
@0xsaya :  as a potential separate issue, I do notice Ethereum’s ᴇɪᴘ‒197 allows having calls with point at infinity being valid. Snarkjs isn’t filtering such Inputs points (the bilinear pairing containing such a point is always 1 whatever the other point is). This breaks the non‑degeneracy criteria of optimal ate pairings that is applied by Zcash…

Does it affects proving systems snarkjs provides or does it affect only other proving systems that Zcash does use ?

**Comment by mimoo** [comment]
ah yeah I ended up writing a similar bug myself in an application due to this (facepalm ^^)
