### ISSUE TITLE
Missing crypto polyfills from the iife build

### ISSUE THREAD

**Issue by StrawberryChocolateFudge** [iden3/snarkjs#362]
Hi

The Crypto polyfill is missing from the iife build here:

https://github.com/iden3/snarkjs/blob/master/config/rollup.iife.config.js#L34

but it's needed here:
https://github.com/iden3/snarkjs/blob/master/src/misc.js#L123

When running it in the browser, zKey.contribute fails with "q.randomBytes is not a function" after getRandomRng asks for entropy.

Solution, add polyfills?

**Comment by phated** [comment]
@StrawberryChocolateFudge I have a proper PR at #364 that you could use instead. And I'll be submitting a PR that adds browser testing for this in a minute.

**Comment by StrawberryChocolateFudge** [comment]
Very cool! I will try it :)
