### ISSUE TITLE
Threads not stopped automatically

### ISSUE THREAD

**Issue by codeblooded1729** [iden3/snarkjs#370]
I have observed that `snarkjs.groth16.prove()` and `snarkjs.groth16.verify()` do not, by default, terminate the threads spawned by stuff like `buildBn128()` which is called internally. But looks like all that needs to be done is call `curve.terminate()` after the job of curve is done. Is there any other solution provided by the library.

**Comment by phated** [comment]
Duplicate of #152 - this is by design.
