### ISSUE TITLE
Better browser handling during zkey contribution

### ISSUE THREAD

**Issue by vimwitch** [iden3/snarkjs#378]
The browser detection [here](https://github.com/iden3/snarkjs/blob/master/src/misc.js#L103) is non-standard. A better test is `typeof window !== 'undefined'`.

This library presents a browser popup asking for entropy during contribution. This is _very_ inappropriate for a library to do. It's the responsibility of the user interface to do this (if desired). I'm requesting that [this logic](https://github.com/iden3/snarkjs/blob/master/src/misc.js#L104) be either removed or optionally disabled.

**Comment by phated** [comment]
If you provide entropy, that function won't be called.

**Comment by vimwitch** [comment]
ah sorry about that, forgot about the contributor name arg
