### ISSUE TITLE
groth16.prove() not working after build

### ISSUE THREAD

**Issue by onuruci** [iden3/snarkjs#396]
Hello there,
snarkjs.groth.prove function failing after taking the  build of the project. I am using react on client side and i can generate proofs of valid inputs without any problem but after taking the build of the project it is failing to do so. The problem is happening on ffjavascript as i traced it with logs. Do you have any suggestions on how to solve the issue. 
This is error log 
```
functors moz-extension://b37ec196-ea24-44fd-9890-d902821133e1/lockdown-install.js:1
    (Async: EventListener.handleEvent)
    functors moz-extension://b37ec196-ea24-44fd-9890-d902821133e1/lockdown-install.js:1
    repairIntrinsics moz-extension://b37ec196-ea24-44fd-9890-d902821133e1/lockdown-install.js:1
    functors moz-extension://b37ec196-ea24-44fd-9890-d902821133e1/lockdown-install.js:1
    <anonymous> moz-extension://b37ec196-ea24-44fd-9890-d902821133e1/lockdown-run.js:4

```

Here are my dependencies and link to my project https://github.com/onuruci/zk_nft

```
"dependencies": {
    "@types/jest": "^26.0.15",
    "@types/node": "^16.11.14",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "circomlib": "^0.5.1",
    "cors": "^2.8.5",
    "ethers": "5.7.2",
    "express": "^4.17.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-json-view": "^1.21.3",
    "react-scripts": "^4.0.0",
    "readline": "^1.3.0",
    "snarkjs": "^0.4.16",
    "styled-components": "^5.2.1",
    "typescript": "^4.1.2",
    "web-vitals": "^1.0.1"
  },
```

**Comment by phated** [comment]
Sounds like you've built it incorrectly. Snarkjs has a custom bundle to run in the browser, so you'd need to emulate that in whatever bundler you are using.

Additionally, you are using an extremely outdated version of snarkjs.

Also, the error log you provided has nothing to do with snarkjs.
