### ISSUE TITLE
Adding TON smart contract generator

### ISSUE THREAD

**Issue by hrmon** [iden3/snarkjs#404]
Hi!
for a recent [competition](https://blog.ton.org/tvm-challenge-is-here-with-over-54-000-in-rewards) in TON community, I tried to implement [TON smart contracts support](https://github.com/hrmon/snarkjs-func/tree/func) for snarkjs (which ranked the best in that competition), like the way it supports solidity right now.

I was wondering if I complete this implementation (cleaning, support for all three protocols and tests), can it be considered to be merged into snarkjs?

**Comment by phated** [comment]
We aren't accepting new verifiers because we can't ensure the correctness of them. You should follow #340 which will enable custom verifier packages once implemented.
