### ISSUE TITLE
Cannot read properties of undefined (reading 'fullProve')

### ISSUE THREAD

**Issue by peter-jim** [iden3/snarkjs#405]
node v19.9.0
macos

I try to use snarkjs on my react dapp. but I awalys get "Cannot read properties of undefined (reading 'fullProve')". I can make sure I had successfully install snarkjs.

**Comment by phated** [comment]
Snarkjs cannot be loaded with required if you are using a bundler. Use our browser bundle or recreate our bundling logic in your bundler.

**Comment by peter-jim** [comment]
thanks ,could you share your browser bundler repo link?
