### ISSUE TITLE
If non-linear constraints  = 0 ,Error: Scalar size does not match

### ISSUE THREAD

**Issue by peter-jim** [iden3/snarkjs#406]
I found a bug ,  If my circuit  non-linear constraints  is  0 . I will got "Error: Scalar size does not match" . if I change my circuit to not zero It work. 

https://zkrepl.dev/ had no problem .

**Comment by ClaudeZsb** [comment]
I just encountered the same error today with a very simple circuit which is used to test false proof generation.

```
pragma circom 2.1.0;

template test() {
    signal input x;
    signal output y;
    var temp = x;
    y <-- (temp ** 3) + temp + 5;
    y === 35;
}

component main = test();
```
With this circuit, you'll meet `Error: Scalar size does not match` at the proving step.

But thanks to @peter-jim , after I add a non-linear constraint, everything goes well.
```
signal xx <== x * x;
```

I don't know if it's a bug or just a result of the underlying proving system. I'm here to confirm what is said by @peter-jim .

**Comment by OBrezhniev** [comment]
If you don't have non-linear constraints, then there's nothing to prove (at least in case of groth16). That's why snarkjs returns error (error message could be better).
