### ISSUE TITLE
How to call `soliditycalldata` in ethereum smart contract runtime?

### ISSUE THREAD

**Issue by jimzk** [iden3/snarkjs#445]
I would like to write a solidity function that accepts parameters in `public.json`. This function will create calldata like what `snarkjs zkey export soliditycalldata` creates, and then send them to `verifyProof` method for zk proof verification. 

The problem is, how to create this calldata at smart contract runtime?

**Comment by TheBojda** [comment]
Check my zk-merkle-tree library for an example: https://github.com/TheBojda/zk-merkle-tree/blob/main/src/zktree.ts#L136
