### ISSUE TITLE
Generating just a witness in browser

### ISSUE THREAD

**Issue by nanaknihal** [iden3/snarkjs#459]
Is there a way to get just the witness in the browser with snarkjs? If not, i'll gladly contribute a PR for it. `snarkjs.wtns.calculate` seems to require an output file to write to, but I want to deal with the witness directly in the browser instead of writing to a file. If there's no such solution, could I make a PR to refactor `snarkjs.wtns.calculate` into two parts: 
`calculateRaw` that just calculates the witness, and the same function `calculate` that now would call `calculateRaw` and save it to a file?

**Comment by OBrezhniev** [comment]
Hi @nanaknihal! Check the js code generated together with wasm files by circom - it works with buffers, and should work in the browser too.

**Comment by nanaknihal** [comment]
Thanks. I didn't try this but was able to get it to work via the `circom_runtime` package:
```javascript
const { WitnessCalculatorBuilder } = require("circom_runtime");

// Loading R1CS and wasm as bytes
const r1cs = fs.readFileSync(`./zk/circuits/circom/artifacts/${circuitName}.r1cs`);
const wasm = fs.readFileSync(`./zk/circuits/circom/artifacts/${circuitName}_js/${circuitName}.wasm`);
 
// Calc witness as bytes without saving any files
const wc = await WitnessCalculatorBuilder(wasm);
const witness =  (wc.circom_version() == 1) ? await wc.calculateBinWitness(inputs) : await wc.calculateWTNSBin(inputs);
