### ISSUE TITLE
Error generating a proof for Circom circuit

### ISSUE THREAD

**Issue by hdvanegasm** [iden3/snarkjs#478]
Hi everyone,

I have the following circuit in circom:

```
// The circuit proves that we know a secret and a polynomial such that the
// Shamir shares are indeed generated from the input secret and the
// input polynomial. Parties are identified as P_1, ..., P_4. The input to the
// circuit are the secret, the coefficients of the polynomial [a_1, a_2]
// used to share the secret, and the number of parties.
pragma circom  2.0.0;

template SecretSharing() {

    signal input secret;
    signal input coefficients[2];

    signal output shares[4];

    for(var i = 1; i <= 4; i++) {
        var eval = 0;
        for(var exp = 0; exp <= 2; exp++) {
            if (exp == 0) {
                eval += secret;
            } else {
                eval += coefficients[exp - 1] * (i ** exp);
            }
        }

        shares[i - 1] <== eval;
    }
}

component main = SecretSharing();
```
The input of the circuit is:

```
{
    "secret": "4",
    "coefficients": [
        "3",
        "4"
    ]
}
```
The circuit compiles correctly and the witness is generated correctly too, however, when I generate the proof with the command:
```
snarkjs groth16 prove secret-sharing_0001.zkey witness.wtns proof.json public.json
```
The output is the following error:

```
[ERROR] snarkJS: Error: Scalar size does not match
    at _multiExp (/usr/local/lib/node_modules/snarkjs/node_modules/ffjavascript/build/main.cjs:4971:19)
    at WasmCurve.multiExpAffine (/usr/local/lib/node_modules/snarkjs/node_modules/ffjavascript/build/main.cjs:5008:22)
    at groth16Prove$1 (/usr/local/lib/node_modules/snarkjs/build/cli.cjs:5768:33)
    at async Object.groth16Prove [as action] (/usr/local/lib/node_modules/snarkjs/build/cli.cjs:12975:36)
    at async clProcessor (/usr/local/lib/node_modules/snarkjs/build/cli.cjs:481:27)
```
How can I solve this error? Thanks.

**Comment by Iverson-cui** [comment]
Maybe you should check other issues. I have come across the same problem now and there are lots of issues about it but I still don't know how.

**Comment by Arvolear** [comment]
Duplicate. Resolved [here](https://github.com/iden3/circom/issues/249).

**Comment by michal-wrzosek** [comment]
Interestingly I get this error even for the example circom circuit. If I try `plonk` instead of `groth16` then I get this error: `Cannot read properties of undefined (reading '0')`.

https://docs.circom.io/getting-started/compiling-circuits/
```
pragma circom 2.0.0;

template Multiplier2() {
    signal input a;
    signal input b;
    signal output c;
    c <== a*b;
 }

 component main = Multiplier2();
```

Making some inputs public also doesn't help. I use snarkjs 0.7.4 and circom 2.1.9 but I also tried older versions and no combinations worked for me so far although I remember 3 years ago all this worked for me.

**Comment by OBrezhniev** [comment]
@michal-wrzosek probably compiler removed these constraints during the simplification pass:
https://docs.circom.io/circom-language/circom-insight/simplification/

@hdvanegasm assigning vars to signals does not create constraints. To fix this refactor your `eval` variable into signal  array.
