### ISSUE TITLE
calculate output without generating proof

### ISSUE THREAD

**Issue by wighawag** [iden3/snarkjs#516]
Is there a way to generate the output from a circom circuit without generating the proof?

I need to compute a circuit logic in the browser and need the proof only after user confirm its full input.

So I would like a way to pass the input and get the output only

Currently I need to execute `snarkjs.groth16.fullProve` and get the `publicSignals` field of the response, but it also generate the proof which I suppose add  some extra computation I would like to avoid

**Comment by Arvolear** [comment]
Hey, there is no need to generate the proof for that. What you are trying to achieve is called "witness testing". You need to compile the circuit with `circom` and locate the `wasm` file it generates.

Then you can do the following:

```ts
await snarkjs.wtns.calculate(inputs, wasmFile, wtnsFile);

const witness = (await snarkjs.wtns.exportJson(wtnsFile)) as bigint[];
```

The `witness[0]` will always be equal to `1` so just skip it. The next values will be a circuit's outputs in the order they are presented in the code.

You can check [zkit](https://github.com/dl-solarity/zkit/blob/4f3e73c801c9cb91bd1457da923e32d0434ec3b6/src/core/CircuitZKit.ts#L64) for reference.
