### ISSUE TITLE
Does snarkjs.groth16.fullProve have any interfaces that feed memory data instead of file paths for wasm and zkey ?

### ISSUE THREAD

**Issue by VictorECDSA** [iden3/snarkjs#523]
Every time JavaScript call snarkjs.groth16.fullProve, does It always have to read the content to the wasm and zkey files? If yes, then when I want to start a service to do proof for many users, each user's every call reads these two files , I wonder if the performance overhead will be huge?

So I want to read the contents of these two files into memory when the service starts, and use wasm and zkey in memory directly every time the user requests generating proof.

Does snarkjs.groth16.fullProve have any interfaces that feed memory data instead of file paths for wasm and zkey ?

**Comment by OBrezhniev** [comment]
Hello! Yes it's possible to read from & write to memory instead of files.
See some examples in https://github.com/iden3/snarkjs/blob/master/test/fullprocess.js and https://github.com/iden3/fastfile/blob/master/test/memfile.test.js
