### ISSUE TITLE
Unable to verify when in WSL2

### ISSUE THREAD

**Issue by yq0810** [iden3/snarkjs#60]
```
  Full process
    ✓ powersoftau new (76ms)
    ✓ powersoftau contribute  (1717ms)
    ✓ powersoftau export challenge
    ✓ powersoftau challenge contribute (1688ms)
    ✓ powersoftau import response (367ms)
    ✓ powersoftau beacon (1706ms)
    ✓ powersoftau prepare phase2 (29497ms)
    1) powersoftau verify
    ✓ zkey new (341ms)
    ✓ zkey contribute  (124ms)
    ✓ zkey export bellman (1550ms)
    ✓ zkey bellman contribute (133ms)
    ✓ zkey import bellman (1803ms)
    ✓ zkey beacon (121ms)
    2) zkey verify
    ✓ zkey export verificationkey
    ✓ witness calculate
    ✓ groth16 proof (111ms)
    3) groth16 verify
```

WSL2 Ubuntu 18.04.4 LTS
Windows 10 Pro 19042.450
node v14.8.0
circom@0.5.18
snarkjs@0.3.16 

I have considered possible environmental issues
I ran the test in docker, the same
https://github.com/eduadiez/snarkjs_tester
```
[INFO]  snarkJS: GET main.b --> 11
[INFO]  snarkJS: SET main.int[999] <-- 7713112592372404476342535432037683616424591277138491596200192981572885523208
[INFO]  snarkJS: GET main.int[999] --> 7713112592372404476342535432037683616424591277138491596200192981572885523208
[INFO]  snarkJS: SET main.c <-- 7713112592372404476342535432037683616424591277138491596200192981572885523208
[INFO]  snarkJS: FINISH: main
[ERROR] snarkJS: Invalid proof
["0x16729f318153579b15da0c352920e8d090edf4591e666713f8394dbbb65bfa3a", "0x0c060e04096d33f36ef7c8c1c1415f704977835822427040cdf87893e5b2b47a"],[["0x1c39ae20ec1dc6894cf64120a5f5d1558cddc3e163780591373c4f86e5398032", "0x2459bede3aceb13a4599206b9c98e494c7541ba5b389732279de8a63b6390110"],["0x1b556bc700d9f555199325835b91edeb29f354567e43660883ee7d3e0ce189bb", "0x27562869095ea22b0806e183f0150cedabdc8e47f51abf6e4006736a35ef52f4"]],["0x2a37638cff971e2305bde2a909d8452a49999b004400e21e31055224419cd5ba", "0x17cf966aae627a38f670846ded3fa0dce9cfd35f15f7072322ec752699ed4853"],["0x110d778eaf8b8ef7ac10f8ac239a14df0eb292a8d1b71340d527b26301a9ab08"]
```

**Comment by JelDe** [comment]
Hello there,
I have the same problem when just trying out the guide. The verification in step 8 does not work.
Interestingly some later verifications do work (steps 18 & 20), but the final proof cannot be verified.
Is this a problem of snarkjs?


`[INFO]  snarkJS: Powers Of tau file OK!
[INFO]  snarkJS: Next challenge hash: {...}
[INFO]  snarkJS: -----------------------------------------------------
[INFO]  snarkJS: Contribution #4: Final Beacon
[INFO]  snarkJS: Next Challenge:  {...}
[INFO]  snarkJS: Response Hash: {...}
[INFO]  snarkJS: Response Hash: {...}
[INFO]  snarkJS: Beacon generator: 0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f
[INFO]  snarkJS: Beacon iterations Exp: 10
[INFO]  snarkJS: Powers Of tau file OK!
[INFO]  snarkJS: -----------------------------------------------------
[INFO]  snarkJS: Contribution #3: Third contribution name
[INFO]  snarkJS: Next Challenge:  {...}
[INFO]  snarkJS: Response Hash: {...}
[INFO]  snarkJS: Response Hash: {...}
[INFO]  snarkJS: Powers Of tau file OK!
[INFO]  snarkJS: -----------------------------------------------------
[INFO]  snarkJS: Contribution #2: Second contribution
[INFO]  snarkJS: Next Challenge:  {...}
[INFO]  snarkJS: Response Hash: {...}
[INFO]  snarkJS: Response Hash: {...}
[INFO]  snarkJS: Powers Of tau file OK!
[INFO]  snarkJS: -----------------------------------------------------
[INFO]  snarkJS: Contribution #1: First contribution
[INFO]  snarkJS: Next Challenge:  {...}
[INFO]  snarkJS: Response Hash: {...}
[INFO]  snarkJS: Response Hash: {...}
[INFO]  snarkJS: -----------------------------------------------------
[ERROR] snarkJS: Phase2 caclutation does not match with powers of tau
`

There seems to be a problem with the first contribution. I tried it also with two contributions (without external software) and only one (might not make sense at all), but I always get stuck at the 8th step.

**Comment by jbaylina** [comment]
Can you check if it's fixed with the last version?

**Comment by benjaminstrasser** [comment]
Currently having a similar issue with version 0.3.25.
Step 18 verification does not work with this error
[ERROR] snarkJS: H section does not match

**Comment by jbaylina** [comment]
Can you provide Node version, OS version and number of cores?

**Comment by benjaminstrasser** [comment]
Another insight .. it works with the circuit provided by the tutorial but not with our own.
The circuit compiles and everything and was successfully used in version 0.1.x

6 cores
Windows 10
ubuntu 20.04 subsystem wsl2
node: v12.18.3

**Comment by jbaylina** [comment]
This should be fixed in the latests versions. It was a problem with systems with a number of cores not a power of two,
