### ISSUE TITLE
Please update README to use stringifyBigInts

### ISSUE THREAD

**Issue by weijiekoh** [iden3/snarkjs#7]
The code in the readme includes these lines:

```
fs.writeFileSync("myCircuit.vk_proof", JSON.stringify(setup.vk_proof), "utf8");
fs.writeFileSync("myCircuit.vk_verifier", JSON.stringify(setup.vk_verifier), "utf8");
```

However, they won't work in Node 10 as bigints can't be serialised. The solution is to use `JSON.stringify(stringifyBigInts(setup.vk_proof)`, as `cli.js` demonstrates.

**Comment by weijiekoh** [comment]
I'd also suggest exporting `stringifyBigInts` and `unstringifyBigInts` in `index.js`.

**Comment by jbaylina** [comment]
The new API in version 0.3 does not require stringify.  The code takes care of it.
