### ISSUE TITLE
no such file or directory: "circuit.wasm" 

### ISSUE THREAD

**Issue by stevekeol** [iden3/snarkjs#74]
When I run the example in nodejs as readme.md, here is something wrong, how can i fix it?
---
errorImage:
![image](https://user-images.githubusercontent.com/11857846/100958782-eed07d80-3557-11eb-84de-7fef2fb2e252.png)

sourcecode:
```js
const snarkjs = require("snarkjs");
const fs = require("fs");

async function run() {
    const { proof, publicSignals } = await snarkjs.groth16.fullProve({a: 10, b: 21}, "circuit.wasm", "circuit_final.zkey");

    console.log("Proof: ");
    console.log(JSON.stringify(proof, null, 1));

    const vKey = JSON.parse(fs.readFileSync("verification_key.json"));

    const res = await snarkjs.groth16.verify(vKey, publicSignals, proof);

    if (res === true) {
        console.log("Verification OK");
    } else {
        console.log("Invalid proof");
    }

}

run().then(() => {
    process.exit(0);
});
```

**Comment by CashCode** [comment]
![image](https://user-images.githubusercontent.com/8258294/101671357-11353000-3a5d-11eb-8bd2-b37ad4cb2392.png)
Errors on browser version

**Comment by phated** [comment]
That error just means your wasm file isn't available where it is being loading automatically by snarkjs.
