### ISSUE TITLE
Errors in the browser version.

### ISSUE THREAD

**Issue by NikitaIT** [iden3/snarkjs#77]
#### fix:
```
 <script>var global = window</script>
 <script src="snarkjs.min.js"></script>
```

#### fix: 
edit snarkjs.js
```
(window || global) .snarkjs = ...
```
and
```
import "snarkjs/dist/snarkjs.js"
```

**Comment by phated** [comment]
The iife build shouldn't be "importable" with ESM, you can just import the normal modules for that, however, I've just submitted a fix for the undefined `global` issue in #85
