### ISSUE TITLE
Feature Request: Remove dependency on wasm for generating witness

### ISSUE THREAD

**Issue by orbmis** [iden3/snarkjs#89]
For compiling large circuits, wasm is problematic, using a native backend as with [snarkit](https://github.com/Fluidex/snarkit) is the only way to compile large circuits.  Would it be possible to update snarkjs to generate a witness without having to use wasm in order to support large circuits?  Wold that involve a large amount of work?

**Comment by phated** [comment]
I believe this is solved by using the circom "2" compiler which is written in rust. The new compiler is available at https://github.com/iden3/circom - there are some changes you need to make to your circuits, but it's fairly straight forward.
