### ISSUE TITLE
How to generate "witness.wtns"  files using snarkjs?

### ISSUE THREAD

**Issue by apianmuse** [iden3/snarkjs#91]
I can't use the following command to generate "witness.wtns" file.
```
>snarkjs wtns calculate circuit.wasm input.json witness.wtns

Error: Invalid Command
```
This command is written on [this page](https://docs.circom.io/4.-generating-zero-knowledge-proofs/circom-and-snarkjs)  and README Guide 22.

My version of snarkjs is 0.3.60.

How should I generate "witness.wtns" files using snarkjs?

**Comment by jacobrosenthal** [comment]
That is indeed the correct command.

I presume you could run the other snarkjs commands? and snark prints its version?
```
$ snarkjs
snarkjs@0.3.60
```
Show the `ls` of that directory. Do you have a circuit.wasm and input.json? circuit.wasm comes from Step 10 https://github.com/iden3/snarkjs#10-compile-the-circuit and input.json comes from Step 22 which shows echoing some json to create the input.json

What OS and version? What version node?

**Comment by apianmuse** [comment]
> That is indeed the correct command.
> 
> I presume you could run the other snarkjs commands? and snark prints its version?
> 
> ```
> $ snarkjs
> snarkjs@0.3.60
> ```
> 
> Show the `ls` of that directory. Do you have a circuit.wasm and input.json? circuit.wasm comes from Step 10 https://github.com/iden3/snarkjs#10-compile-the-circuit and input.json comes from Step 22 which shows echoing some json to create the input.json
> 
> What OS and version? What version node?

OS:Linux

I have circuit.wasm and input.json

```
$ npm ls snarkjs
snarkjs@0.3.60
$ circom circuit.circom --r1cs --wasm --sym
$ snarkjs wtns calculate circuit.wasm input.json witness.wtns
Error: Invalid Command
    at run (/home/pyc/nodejs/lib/node_modules/snarkjs/cli.js:450:19)
    at Object.<anonymous> (/home/pyc/nodejs/lib/node_modules/snarkjs/cli.js:295:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
ERROR: Error: Invalid Command
```

**Comment by jacobrosenthal** [comment]
Again, what version of node are you on? `node --version`
The project requires node14 thats my current best guess
https://github.com/iden3/snarkjs#install-node-v14

**Comment by apianmuse** [comment]
> Again, what version of node are you on? `node --version`
> The project requires node14 thats my current best guess
> https://github.com/iden3/snarkjs#install-node-v14

my node version is v14.16.1

**Comment by drewstone** [comment]
Seems the API has changed, try something like:
```
snarkjs calculatewitness -c artifacts/circuits/circuit.wasm -i input.json -w witness.wtns
```

**Comment by phated** [comment]
Witness calculation is primarily done from the code that circom generates now. SnarkJS **tries** to support the different versions of circom2 witness generation but there is generally a time delay between their breaking changes and our updates. So please use the witness generator that circom outputs.
